-- AlterTable
ALTER TABLE `colaborador` MODIFY `status` ENUM('ATIVO', 'DESIGNADO', 'COMISSIONADO', 'PTTC', 'DESATIVADO') NOT NULL DEFAULT 'ATIVO';

-- AlterTable
ALTER TABLE `usuario` ADD COLUMN `status` ENUM('ATIVO', 'DESATIVADO') NOT NULL DEFAULT 'ATIVO';
